### ISSUE TITLE
Let us set price ranges to avoid 3rd party sellers/price gouging

### ISSUE THREAD

**Issue by chineeboy** [jef/nvidia-snatcher#310] opened 2020-09-25 16:07 UTC
### Description

Let us define a min and max price range so we can avoid price gougers and 3rd party sellers.  We'll only get notified when stock is available and falls within our specified price range.

### Possible solution

scanning the price tag and only notify if it falls within the price range specified in .env
MIN_PRICE="699.99"
MAX_PRICE="1199.99"

**Comment by wedge22** [comment] 2020-09-25 16:12
I just suggested the same implementation in another issues post, I fully support this idea.

**Comment by xninjax** [comment] 2020-09-25 16:15
Yes this would be very beneficial in combating scalpers.

**Comment by geman220** [comment] 2020-09-25 21:45
Is this only happening on Amazon?  The reason I ask is due to the fact that implementation is a bit more complex than just adding a min/max price filter.  For example, a 3070 would have a different min/max than a 3090.  I mean, we can make it so everything has different min/max configurations but that's a lot of rework if the problem is only Amazon.  **If** the problem is only happening on Amazon we could try to re-implement the "banned seller" feature which will disallow positives from Sellers who are known to scalp on Amazon.

**Comment by chineeboy** [comment] 2020-09-25 21:53
> Is this only happening on Amazon? The reason I ask is due to the fact that implementation is a bit more complex than just adding a min/max price filter. For example, a 3070 would have a different min/max than a 3090. I mean, we can make it so everything has different min/max configurations but that's a lot of rework if the problem is only Amazon. **If** the problem is only happening on Amazon we could try to re-implement the "banned seller" feature which will disallow positives from Sellers who are known to scalp on Amazon.

I can only speak for Amazon.ca and newegg.ca, they both allow 3rd party sellers

**Comment by geman220** [comment] 2020-09-25 21:54
I wasn't aware Newegg allowed 3rd party sellers.  I still think it might be easier to disallow sellers that you can add in `.env` since again, price ranges would be hard to implement across 3 different cards with different price ranges, although not impossible.

**Comment by chineeboy** [comment] 2020-09-25 21:58
> I wasn't aware Newegg allowed 3rd party sellers. I still think it might be easier to disallow sellers that you can add in `.env` since again, price ranges would be hard to implement across 3 different cards with different price ranges, although not impossible.

what if we had prices for each card? and to be honest, max price would be useful, min price less so.

something like max_price_2090, max_price_3080, max_price_3070.?

**Comment by geman220** [comment] 2020-09-25 22:05
> > I wasn't aware Newegg allowed 3rd party sellers. I still think it might be easier to disallow sellers that you can add in `.env` since again, price ranges would be hard to implement across 3 different cards with different price ranges, although not impossible.
> 
> what if we had prices for each card? and to be honest, max price would be useful, min price less so.
> 
> something like max_price_2090, max_price_3080, max_price_3070.?

Well, that's what I was saying, that is _possible_.  But that means 3x the work.  You need to set up 3 new environment variables and tie logic 3x over.  Instead of either doing a `banned seller` or `allowed seller`.  Which would be a single environment variable to accomplish the same end goal to avoid scalpers.

**Comment by MrRobot245** [comment] 2020-09-25 22:16
Instead of a price range why not just do max price? Set it to the highest value for the most expensive card +100 or so, other prices will probably be scalpers

**Comment by geman220** [comment] 2020-09-25 22:17
> Instead of a price range why not just do max price? Set it to the highest value for the most expensive card +100 or so, other prices will probably be scalpers

Because if I want a 3080, it's reasonable to get scalper false-positives at $1400 which is the price of a 3090.  That's still 2x the cost of a 3080.

**Comment by MrRobot245** [comment] 2020-09-25 22:26
> Because if I want a 3080, it's reasonable to get scalper false-positives at $1400 which is the price of a 3090.  That's still 2x the cost of a 3080.

Haha not in Canadian beaver bucks 😔 but it would probably be more universal to do a max price for 70/80/90 than tying an 'allowed_seller' for each store?

**Comment by geman220** [comment] 2020-09-25 23:09
`bannedSeller` has been merged.  See #270

**Closed** 2020-09-25 23:09 UTC
Labels: enhancement

**Comment by csoyuncu** [comment] 2021-04-15 22:47
any fix this problem ? cheaters buy RTX 3090 to 900$!
