### ISSUE TITLE
Does not play MP3 notification

### ISSUE THREAD

**Issue by lexarflash8g** [jef/nvidia-snatcher#184] opened 2020-09-22 00:03 UTC
Upon running npm run test:notification

I get a code break..
and my .env file has this PLAY_SOUND="promise.mp3"
with the mp3 file in the nvidia-snatcher folder

[5:01:23 PM] error :: error playing sound: Error: Couldn't find a suitable audio player
C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146
      throw new Error(d.errors[0], res)
      ^

Error: application token is invalid
    at Pushover.errors (C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:146:13)
    at IncomingMessage.<anonymous> (C:\nvidia-snatcher\node_modules\pushover-notifications\lib\pushover.js:250:12)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nvidia-snatcher@1.4.0 test:notification: `npm run build && node build/__test__/notification-test.js`

**Comment by vp-cshow** [comment] 2020-09-22 00:15
You must have a command line audio player supported by the library that's being used to play the sound. Others have reported success with mplayer and mpg123. You can place it in the same folder as the program.

Duplicate of #116

**Comment by lexarflash8g** [comment] 2020-09-22 00:25
I extracted mplayer.exe into nvidia-snatcher folder and it still give the same error

![image](https://user-images.githubusercontent.com/10263702/93834056-65373200-fc2f-11ea-9fa0-de3c2a64df2c.png)

**Comment by vp-cshow** [comment] 2020-09-22 00:35
Which error? The one related to the sound player, or the one related to pushover?

**Comment by lexarflash8g** [comment] 2020-09-22 00:37
Im getting the push-over error what is causing this .. the mp3 player?

**Comment by lexarflash8g** [comment] 2020-09-22 00:40
Oh I fixed it now.. just put empty for the PUSHOVER_TOKEN
what does that do..
Any how do I get the SMS notification to send to my phone?
I get the email but no SMS

**Comment by lexarflash8g** [comment] 2020-09-22 00:45
Oh I see its an app that sends notifications.. I signed up for it and linked it thanks.. but I dont need the token just the key

Also it seems like it is not searching Nvidia and I put that under the "stores" in the .ENV file
it checks EVGA,newegg, amazon etc..

**Comment by jef** [comment] 2020-09-22 02:52
https://github.com/jef/nvidia-snatcher/issues/116

**Closed by jef** 2020-09-22 02:52 UTC
Labels: bug, duplicate
