### ISSUE TITLE
Error playing sound: Error: Couldn't find a suitable audio player

### ISSUE THREAD

**Issue by andredevelops** [jef/nvidia-snatcher#228] opened 2020-09-23 02:03 UTC
### Description

NVIDIA Snatcher seems to error out when trying to find an audio player to play the notification.mp3 file in the root directory of the script. 

I've been helping out users configure this script, and they all run into the same issue. Their operating systems are Windows 10. 

I have a copy of one of the user's error output located here: https://imgur.com/oiuQ7cS

Tried switching to vlc as the default .mp3 player in windows in the hope that it was just having issues opening up the default sound player (groove or windows media center player). 

Attempted to change PLAY_SOUND="notification" to PLAY_SOUND="", and PLAY_SOUND=false, but the issue persists. 

Sometimes the script can run for 20 minutes without the issue, and other times it crashes almost immediately. 

Thanks

**Comment by vp-cshow** [comment] 2020-09-23 02:08
Duplicate of #116

More info here: https://github.com/jef/nvidia-snatcher/issues/116#issuecomment-695822452

If no one gets around to it by then, I'll look into adding this to the wiki + submit a PR to update the readme sometime tomorrow.

**Comment by geman220** [comment] 2020-09-23 02:15
Added to the wiki https://github.com/jef/nvidia-snatcher/wiki/Installation:-Windows

**Closed by geman220** 2020-09-23 02:15 UTC
Labels: bug
