### ISSUE TITLE
Best Buy pause before checking if in-stock

### ISSUE THREAD

**Issue by rodalpho** [jef/nvidia-snatcher#280] opened 2020-09-24 17:58 UTC
On the awful Best Buy website, when you first load the page, it will often show yellow "add to cart" buttons, then a couple seconds later a secondary process refreshes and they properly show "sold out" grey buttons. Is it possible to implement a 4 second pause before checking if product shows in stock?

**Comment by geman220** [comment] 2020-09-24 18:01
Duplicate of #277 

This function already exists IN_STOCK_WAIT_TIME="30" Time to wait between requests to the same store if it has cards in stock in seconds.

https://github.com/jef/nvidia-snatcher#customization

**Closed by geman220** 2020-09-24 18:01 UTC
Labels: duplicate

**Comment by rodalpho** [comment] 2020-09-24 18:03
No, this is not a duplicate and that does not address the issue. 

I'm aware of the in stock wait time, and I have it set all the way up to 15 minutes now because of false positive alerts on Best Buy. If those false positives were addressed that would no longer be necessary.

**Comment by jef** [comment] 2020-09-24 21:44
They aren't false positives. They are positives. Best Buy showed "Add to cart" all morning.

**Comment by rodalpho** [comment] 2020-09-25 16:34
That's a different issue and I agree there's no way to fix that specific problem. Followup in #281 after this one was closed.
