### ISSUE TITLE
MAC copy .env-example doesn't work

### ISSUE THREAD

**Issue by yarkon55** [jef/nvidia-snatcher#658] opened 2020-11-01 11:36 UTC
When I'm trying to copy .env-example .env ;
it says "-bash: copy: command not found"
Can someone help me?
mac OS Catalina 10.15.7

**Comment by rotemgrim** [comment] 2020-11-01 11:44
Its not mac support forum.
and its clearly not a bug.

**Comment by yarkon55** [comment] 2020-11-01 11:48
Nvidia-snatcher not only for windows, and it is bug because it is a problem. Maybe someone with Mac OS encountered this issue too.

**Comment by shortywz** [comment] 2020-11-01 15:22
This isn't a bug - you're not using the correct command to copy a file. Basic knowledge of the command shell is required to get this up and running.

'copy' is not how you copy a file in macos - the correct command is 'cp'.

**Comment by yarkon55** [comment] 2020-11-01 15:27
Okay, thank you. I never before used command shell so I don't have a clue what commands I need

**Comment by yarkon55** [comment] 2020-11-01 15:38
Now I have this issue:
cp: .env-example: No such file or directory
However I have Nvidia snatcher folder

**Comment by mtraynham** [comment] 2020-11-01 21:42
`cp .env-example .env`

@yarkon55, I encourage you to instead close this bug, use [StackOverflow](https://stackoverflow.com/) or [Google](https://lmgtfy.app/?q=linux+cp+command) for a general overview of command shells and using [`man`](https://kb.iu.edu/d/afjm) to read the manual for certain commands.  For example, `man cp`.

**Comment by yarkon55** [comment] 2020-11-01 22:16
I appreciate your help, but I still have this issue:
-bash: cd: nvidia-snatcher: No such file or directory
And I can't still find env file in my folder

And I don't want to read all this stuff to just get one program working, I thought that it is a regular issue and you can help me, I don't know a thing about js and don't want to get into, to run 1 program. So please just tell me what I need to type.

**Comment by iseduced** [comment] 2020-11-02 11:20
> I appreciate your help, but I still have this issue:
> -bash: cd: nvidia-snatcher: No such file or directory
> And I can't still find env file in my folder
> 
> And I don't want to read all this stuff to just get one program working, I thought that it is a regular issue and you can help me, I don't know a thing about js and don't want to get into, to run 1 program. So please just tell me what I need to type.

While there are several ways to do it, here's an easy way to get you started with the mac terminal. Access the directory that nvidiasnatcher is installed in utilizing the two commands below:

1. ls (this command prints the folders and files in a directory)
2. cd foldername (this command enters a specific folder)

Once you've accessed the nvidiasnatcher folder, you'll notice that using the ls command won't display the .env-example file or any other file that starts with a ".", you can display them by using ls -a

You can copy the file inside the folder by using the command:
cp .env-example .env

Then you can delete .env-example with the command:
rm .env-example

Then you can edit .env with the command:
open -a TextEdit .env

**Comment by yarkon55** [comment] 2020-11-02 16:43
Hi, it doesn't check usa amazon, and b&h but I put them in file.
It saying this:
error :: ✖ [nvidia] Unknown country usa,canada

**Comment by jef** [comment] 2020-11-02 20:11
Thanks for all the help everyone. I'm going to close this issue, but feel free to continue to ask for help on setting up the bot.

**Comment by jef** [comment] 2020-11-02 20:11
> Hi, it doesn't check usa amazon, and b&h but I put them in file.
> It saying this:
> error :: ✖ [nvidia] Unknown country usa,canada

What's your `.env` look like now after you copied it over?

**Closed by jef** 2020-11-02 20:11 UTC
Labels: type: bug

**Comment by jef** [comment] 2020-11-02 20:12
> Then you can delete .env-example with the command:
> `rm .env-example`

I would suggest not removing `.env-example` in case someone would like to revert back to defaults or have it has reference.

**Comment by yarkon55** [comment] 2020-11-02 20:29
It looks like this:
COUNTRY="usa,canada"
DESKTOP_NOTIFICATIONS="true"
IN_STOCK_WAIT_TIME="0"
LOG_LEVEL="info"
MAX_PRICE_SERIES_3070="900"
NVIDIA_ADD_TO_CART_ATTEMPTS="20"
OPEN_BROWSER="true"
PAGE_TIMEOUT="100000"
SCREENSHOT="false"
SHOW_ONLY_BRANDS="asus,evga,gigabyte,msi,nvidia,zotac"
SHOW_ONLY_SERIES="3070"
STORES="amazon,bandh,bestbuy,bestbuy-ca,newegg,newegg-ca"

But I don't see any amazon or bandh in checks, and can I choose 2 countries? Or I need to only choose one

**Comment by jef** [comment] 2020-11-02 20:36
`COUNTRY` is only in use for `nvidia`, which is deprecated. (I should put a log note.).

I'd also remove `NVIDIA_ADD_TO_CART_ATTEMPTS`.

**Comment by yarkon55** [comment] 2020-11-02 21:28
Didn't help, still can't see b&h and amazon(

**Comment by jef** [comment] 2020-11-03 04:42
I'd also include your `USER_AGENT`. They could be blocking requests from the default agent.

**Comment by yarkon55** [comment] 2020-11-03 10:20
Do I need to put something in it? Or just leave like that "USER_AGENT="

**Comment by yarkon55** [comment] 2020-11-03 10:24
I leave it empty and still don't search amazon and b&h

**Comment by jef** [comment] 2020-11-03 22:40
Get your user agent [here](https://www.google.com/search?q=what+is+my+user+agent)

and set it like this:

```
USER_AGENT=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
```

**Comment by yarkon55** [comment] 2020-11-03 22:43
Is this good: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15  
?

**Comment by jef** [comment] 2020-11-03 22:43
Looks good to me.

**Comment by yarkon55** [comment] 2020-11-03 22:45
I pasted it, but still doesn't search amazon)

**Comment by jef** [comment] 2020-11-03 22:46
Do a more minimal config like this:

```
STORES=amazon
```

What does it print out?

**Comment by yarkon55** [comment] 2020-11-03 22:47
I don't need brackets there?
Like I suppose to do this right? STORES="amazon"

**Comment by jef** [comment] 2020-11-03 22:47
Go through these steps: https://github.com/jef/nvidia-snatcher/issues/663

Let me know if you still have issues.

**Comment by jef** [comment] 2020-11-03 22:47
> I don't need brackets there?
> Like I suppose to do this right? STORES="amazon"

You can use with or without quotes.

**Comment by yarkon55** [comment] 2020-11-03 22:50
I have tried npm i && npm run start , but still same
Going to try your next suggestion

**Comment by yarkon55** [comment] 2020-11-03 22:52
I don't have nvidia-snatcher folder in nvidia-snatcher, so what do I do next?

**Comment by jef** [comment] 2020-11-03 23:02
Try and use `HEADLESS=false`

Here's my config that I just tested with:

```
STORES=amazon,bandh,evga
HEADLESS=false
USER_AGENT=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
```

```
                    $$\       $$\ $$\                                                  $$\               $$\
                    \__|      $$ |\__|                                                 $$ |              $$ |
$$$$$$$\ $$\    $$\ $$\  $$$$$$$ |$$\  $$$$$$\           $$$$$$$\ $$$$$$$\   $$$$$$\ $$$$$$\    $$$$$$$\ $$$$$$$\   $$$$$$\   $$$$$$\
$$  __$$\\$$\  $$  |$$ |$$  __$$ |$$ | \____$$\ $$$$$$\ $$  _____|$$  __$$\  \____$$\\_$$  _|  $$  _____|$$  __$$\ $$  __$$\ $$  __$$\
$$ |  $$ |\$$\$$  / $$ |$$ /  $$ |$$ | $$$$$$$ |\______|\$$$$$$\  $$ |  $$ | $$$$$$$ | $$ |    $$ /      $$ |  $$ |$$$$$$$$ |$$ |  \__|
$$ |  $$ | \$$$  /  $$ |$$ |  $$ |$$ |$$  __$$ |         \____$$\ $$ |  $$ |$$  __$$ | $$ |$$\ $$ |      $$ |  $$ |$$   ____|$$ |
$$ |  $$ |  \$  /   $$ |\$$$$$$$ |$$ |\$$$$$$$ |        $$$$$$$  |$$ |  $$ |\$$$$$$$ | \$$$$  |\$$$$$$$\ $$ |  $$ |\$$$$$$$\ $$ |
\__|  \__|   \_/    \__| \_______|\__| \_______|        \_______/ \__|  \__| \_______|  \____/  \_______|\__|  \__| \_______|\__|
1.7.0

[6:00:59 PM] warn :: evga is deprecated since they only support queuing
[6:00:59 PM] info :: ℹ selected stores: amazon, bandh, evga
[6:00:59 PM] info :: ℹ selected series: 3070, 3080, 3090
[6:00:59 PM] info :: ✔ sound player found: afplay
[6:01:04 PM] error :: Failed to parse card: PNY GeForce RTX 3070 8GB Dual Fan Ampere Graphics Card
[6:01:05 PM] error :: Failed to parse card: PNY NVIDIA GeForce RTX 3070 Dual Fan 8GB GDDR6 Ray-Tracing Graphics Card, 5888 Core, 1500MHz GPU, 1725MHz Boost
[6:01:14 PM] info :: ✖ [amazon] [pny (3080)] xlr8 :: OUT OF STOCK
[6:01:16 PM] info :: ✖ [bandh] [gigabyte (3080)] gaming oc :: OUT OF STOCK
[6:01:18 PM] info :: ✖ [amazon] [pny (3080)] xlr8 rgb :: OUT OF STOCK
[6:01:20 PM] info :: ✖ [bandh] [zotac (3080)] trinity :: OUT OF STOCK
[6:01:21 PM] info :: ✖ [amazon] [msi (3080)] gaming x trio :: OUT OF STOCK
[6:01:24 PM] info :: ✖ [bandh] [msi (3080)] gaming x trio :: OUT OF STOCK
```

If you don't see the browser using those links, I would delete the folder and reclone and start from the beginning.

**Comment by yarkon55** [comment] 2020-11-03 23:07
YEP, its working , but it reload cards on amazon and it just swap my screen to chronium, how to set that it would run in bg

**Comment by yarkon55** [comment] 2020-11-04 06:46
Any help on that?

**Comment by jef** [comment] 2020-11-04 20:29
I'd remove the `HEADLESS=false` part.
