### ISSUE TITLE
PAGE_SLEEP_MIN being ignored?

### ISSUE THREAD

**Issue by daviderickson** [jef/nvidia-snatcher#510] opened 2020-10-12 19:24 UTC
### Description

Hi running on Windows 10, my .env has configured PAGE_SLEEP_MIN (and PAGE_BACKOFF_MIN) both to 60000, so I'd expect a 60 second minimum delay between queries to the same store.  However from the log printout I'm getting:

[12:18:06 PM] info :: ✖ [nvidia] [nvidia (3080)] founders edition :: OUT OF STOCK
[12:18:10 PM] info :: ✖ [nvidia] [nvidia (3080)] founders edition :: OUT OF STOCK
[12:19:13 PM] info :: ✖ [nvidia] [nvidia (3080)] founders edition :: OUT OF STOCK
[12:19:17 PM] info :: ✖ [nvidia] [nvidia (3080)] founders edition :: OUT OF STOCK

Which looks to me like the min value isn't being respected by the backend.

Thanks!

**Comment by xninjax** [comment] 2020-10-13 01:16
Hi @daviderickson, just wondering if your running the latest nvidia-snatcher? if you haven't done an update in a while, it may be worth doing so, as this issue should have been resolved in https://github.com/jef/nvidia-snatcher/pull/465#issue-498918401.

Alternately, you can try setting PAGE_SLEEP_MAX to 60000 as well, as this would be a workaround fix (if you haven't pulled a recent update/ or don't want to yet).  

Let us know if either of these resolve the issue for you 👍

**Comment by jef** [comment] 2020-10-13 17:05
Going to close and we can reopen if it ends up being a regression. Thanks @xninjax.

**Comment by daviderickson** [comment] 2020-10-13 18:01
@xninjax @jef Yeah I pulled yesterday, I'm on f24f56549e16dc7f9147ccb03ee5715ef51f0e75 same problem.

**Comment by andrewmackrodt** [comment] 2020-10-13 18:44
Looks like intended behaviour, the 3080 FE has 2 entries using different pages IIRC, same as the 3090. I was also confused by this behaviour when I first used the project, like @daviderickson I expected `PAGE_SLEEP_MIN` to be `a 60 second minimum delay between queries to the same store`. However, it acts as a delay between batches of queries to the same store.

**Comment by xninjax** [comment] 2020-10-13 19:29
Agreed the multiple hits can appear broken/confusing at first, but indeed the script is confirmed only checking one link per series per batch (i.e every 60sec here).  2 links per series on nvidia sore ✔️ 

![image](https://user-images.githubusercontent.com/23090488/95905138-b1205700-0d55-11eb-8521-89e82fa6ac58.png)
* logger.info `delay` added for debug purposes

**Closed** 2020-10-13 21:30 UTC
Labels: type: bug
