### ISSUE TITLE
Could not find files for the given pattern(s)

### ISSUE THREAD

**Issue by AzothCrow** [jef/nvidia-snatcher#182] opened 2020-09-21 23:17 UTC
I'm getting the following when I run the snatcher;

> nvidia-snatcher@1.4.0 start C:\nvidia-snatcher
> npm run build && node build/index.js

> nvidia-snatcher@1.4.0 build C:\nvidia-snatcher
> rimraf ./build && tsc

INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
[7:07:38 PM] info :: ✖ [nvidia] still out of stock: nvidia founders edition

This is my .env setup;

DESKTOP_NOTIFICATIONS="true"
EMAIL_USERNAME=REDACTED
EMAIL_PASSWORD=REDACTED
HEADLESS="true"
IN_STOCK_WAIT_TIME="10"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PHONE_NUMBER=REDACTED
PHONE_CARRIER="google"
PLAY_SOUND="notification.mp3"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
SHOW_ONLY_SERIES="3080"
STORES="bestbuy,bandh,nvidia,newegg,evga,asus"
SCREENSHOT="true"
USER_AGENT=REDACTED

I'm like 90% sure I installed everything correctly as the instructions are pretty clear. Any insight?

**Comment by Indomitous** [comment] 2020-09-21 23:32
Make sure to rename the .env-example to .env

I was getting the same error and realized I forgot to do that. After changing it, it gave the INFO:"" error but then began working like it should.

**Comment by AzothCrow** [comment] 2020-09-21 23:36
![image](https://user-images.githubusercontent.com/53837673/93831803-ba7c3f00-fc41-11ea-8d87-82b4fa7813b3.png)

**Comment by vp-cshow** [comment] 2020-09-22 00:15
You must have a command line audio player supported by the library that's being used to play the sound. Others have reported success with mplayer and mpg123. You can place it in the same folder as the program.

Duplicate of #116

**Comment by AzothCrow** [comment] 2020-09-22 00:36
Hm, even without the sound its still not providing updates for any of the websites other than Nvidia itself.

**Comment by vp-cshow** [comment] 2020-09-22 01:25
This is an issue with your `.env`. If the bot thinks it's missing, it'll default to nvidia only. Check the extensions of your files; make sure `.env` isn't really `.env.txt` or `.env.env`.

**Comment by StruttinSoul** [comment] 2020-09-22 01:53
The issue is that your file named '.env' has a .txt extension to it (you can tell based off of the file type). Click on View at the top of the explorer window and ensure you have 'File Name Extensions' checked off under the show/hide section - once that's done you should see the .txt extension that's appended to the .env file. Simply delete the .txt off the end and that should do it.

**Comment by jef** [comment] 2020-09-22 03:27
> The issue is that your file named '.env' has a .txt extension

We really need to write up something in the wiki.

Thanks for the help y'all. Going to close.

**Closed by jef** 2020-09-22 03:27 UTC
Labels: bug
