### ISSUE TITLE
Allow per-URL blocklisting of checked items

### ISSUE THREAD

**Issue by shaver** [jef/nvidia-snatcher#313] opened 2020-09-25 17:54 UTC
### Description

Sometimes a store will have an item in stock that isn't interesting (scalped price, for example) but still causes notifications. I'd like to be able to block them on a per-URL instance to keep them from being considered or using CPU time to poll.

### Possible solution

Pipe-delimited list in SKIP_PRODUCT_URLS= configuration item? SKIP_URL_COUNT=3/SKIP_URL_1/SKIP_URL_2/SKIP_URL_3 ?

**Comment by geman220** [comment] 2020-09-25 21:46
Dupe of #310

**Closed by geman220** 2020-09-25 21:46 UTC
Labels: enhancement

**Comment by shaver** [comment] 2020-09-25 21:58
I don't think it's a dupe of that one, but you could use both of them to deal with the specific scalping problem. It wouldn't help for long ship times, a seller you don't want to deal with, someone that doesn't ship to your country, etc.
