### ISSUE TITLE
add specific model of card, besides the brand?

### ISSUE THREAD

**Issue by shinfo44** [jef/nvidia-snatcher#232] opened 2020-09-23 03:37 UTC
Now that I've gotten this working beautifully, is there any way to get an alert for a specific model of card, for example an EVGA FTW3, instead of just EVGA?

I'm sure there might be an answer somewhere but I'm still new to GitHub and I'm not having luck with my search, sorry!

**Comment by geman220** [comment] 2020-09-23 04:28
I believe this may be a duplicate of #30

**Comment by igniscyan** [comment] 2020-09-23 05:51
Can someone point me to where in code it knows to check for certain listings? A dirty and quick workaround for now would be to offer the ability to filter out specific models "EX: 'black' in .env".

**Comment by fokeiro2020** [comment] 2020-09-23 18:27
> Now that I've gotten this working beautifully, is there any way to get an alert for a specific model of card, for example an EVGA FTW3, instead of just EVGA?
> 
> I'm sure there might be an answer somewhere but I'm still new to GitHub and I'm not having luck with my search, sorry!

did u get notifications working ?

**Comment by jef** [comment] 2020-09-23 18:49
Duplicate of #30

You can filter by using `SHOW_ONLY_BRANDS` and `SHOW_ONLY_SERIES`.

https://github.com/jef/nvidia-snatcher#customization

**Closed by jef** 2020-09-23 18:49 UTC
Labels: duplicate

**Comment by shinfo44** [comment] 2020-09-23 19:15
> 
> 
> Duplicate of #30.
> 
> You can filter by using `SHOW_ONLY_BRANDS` and `SHOW_ONLY_SERIES`.
> 
> https://github.com/jef/nvidia-snatcher#customization

Apologises, does this mean I can filter by model now? So how would I update the /env file to reflect only wanting a FTW3, for exmaple?

**Comment by igniscyan** [comment] 2020-09-23 19:19
> Duplicate of #30.
> 
> 
> 
> You can filter by using `SHOW_ONLY_BRANDS` and `SHOW_ONLY_SERIES`.
> 
> 
> 
> https://github.com/jef/nvidia-snatcher#customization

I believe this issue refers to filtering by card model, not by brand and series.
