### ISSUE TITLE
Sound not playing

### ISSUE THREAD

**Issue by stlmike** [jef/nvidia-snatcher#86] opened 2020-09-19 23:57 UTC
With the latest the sound stop working for me.  I fixed it by editing

notification.ts

removed

	if (notifications.playSound === 'true') {
		playSound();
	}

And Changed 

	if (notifications.email.username && notifications.email.password) {
		playSound();
		sendEmail(cartUrl);
	}

Sound playing again.  something with the if statement is not working right???

**Comment by gangwarily** [comment] 2020-09-20 00:06
Noticed this also. It seems like `notifications.playSound` was previously being used for the filename of the sound file and now its being incorrectly used for both the filename and true/false condition for whether the sound should be played.

**Comment by jef** [comment] 2020-09-20 02:26
I believe #83 solves this.

**Comment by geman220** [comment] 2020-09-20 05:56
Potentially solved in #91

**Comment by ththiem** [comment] 2020-09-20 06:51
This still runs afoul of a limitation in the play-sound library being used that throws this error:
`error :: error playing sound: Error: Couldn't find a suitable audio player`

Due to the limitation of the library requiring:
-     mplayer
-     afplay
-     mpg123
-     mpg321
-     play
-     omxplayer
-     aplay
-     cmdmp3

To play audio.

**Comment by jef** [comment] 2020-09-20 12:39
Duplicate of #76. Closing.

**Closed by jef** 2020-09-20 12:39 UTC
Labels: bug, duplicate
