### ISSUE TITLE
error :: ✖ [nvidia] Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by poly-mathic** [jef/nvidia-snatcher#359] opened 2020-09-28 13:32 UTC
### Description

After running successfully for about a minute [nvidia] starts throwing an error that says unexpected token < in JSON at position 0
It still seems to succeed at checking every so often but it is throwing more errors than successes. Any suggestions? I'm not a programmer. 
![Screenshot 2020-09-28 093113](https://user-images.githubusercontent.com/28655581/94438645-64d9f200-016d-11eb-931a-2b8bbafd9cfe.png)

Here is my .env, made minimal changes:
OS: Windows
 
BROWSER_TRUSTED=""
DESKTOP_NOTIFICATIONS="true"
DISCORD_NOTIFY_GROUP=""
DISCORD_WEB_HOOK=""
EMAIL_USERNAME=""
EMAIL_TO=""
EMAIL_PASSWORD=""
HEADLESS=""
IN_STOCK_WAIT_TIME=""
LOG_LEVEL=""
LOW_BANDWIDTH=""
MICROCENTER_LOCATION=""
NVIDIA_ADD_TO_CART_ATTEMPTS=""
NVIDIA_SESSION_TTL=""
OPEN_BROWSER="true"
PAGE_TIMEOUT=""
PHONE_NUMBER=""
PHONE_CARRIER=""
PLAY_SOUND="got-it-done.mp3"
PUSHBULLET=""
PUSHOVER_TOKEN=""
PUSHOVER_USER=""
PUSHOVER_PRIORITY=""
PAGE_BACKOFF_MIN=""
PAGE_BACKOFF_MAX=""
PAGE_SLEEP_MIN=""
PAGE_SLEEP_MAX=""
SHOW_ONLY_BRANDS=""
SHOW_ONLY_MODELS="founders edition"
SHOW_ONLY_SERIES="3080"
SLACK_CHANNEL=""
SLACK_TOKEN=""
STORES="nvidia-api,nvidia,bestbuy"
COUNTRY=""
SCREENSHOT="false"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID=""
TWITTER_CONSUMER_KEY=""
TWITTER_CONSUMER_SECRET=""
TWITTER_ACCESS_TOKEN_KEY=""
TWITTER_ACCESS_TOKEN_SECRET=""
TWITTER_TWEET_TAGS=""
USER_AGENT=""

**Comment by poly-mathic** [comment] 2020-09-28 13:40
Never mind, as of now i'm no longer seeing this so I'll close. I'd like to know that happened though if anyone can explain.

**Comment by JeffyW** [comment] 2020-09-28 16:55
I'm seeing this come and go.  If I stop and restart it goes away for some period of time but has been coming back.  It seems like this is occurring due to the call to "Refresh session token":

![image](https://user-images.githubusercontent.com/8570706/94462624-aa4bee80-0170-11eb-8e33-59dfd685009b.png)

**Comment by poly-mathic** [comment] 2020-09-28 17:05
Yeah its still happening for me as well, restarting fixes it for a moment

**Comment by JeffyW** [comment] 2020-09-28 17:07
It seems to only be occurring for nvidia-api, not plain nvidia as a store.

I think it's related to #347

**Comment by andrewmackrodt** [comment] 2020-09-28 17:10
> It seems to only be occurring for nvidia-api, not plain nvidia as a store.
> 
> I think it's related to #347

Thanks, having a look at it now.

**Comment by xninjax** [comment] 2020-09-28 17:46
I just opened issue https://github.com/jef/nvidia-snatcher/issues/363#issue-710457570

I think this may be the cause - with no value in .env supplied, it appears the token refresh is rapid, and not taking the 60000ms default.  ??

**Comment by andrewmackrodt** [comment] 2020-09-28 18:10
Should be fixed in #364, thanks @xninjax for tracking down the source of the error!

**Closed by andrewmackrodt** 2020-09-28 18:10 UTC
Labels: bug
