### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by 480s** [jef/nvidia-snatcher#663] opened 2020-11-02 18:01 UTC
### Description

re installed everything and now this message 

```
npm ERR! missing script: start
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...
------------------------------------------------------------------
package.json

{
  "name": "nvidia-snatcher",
  "description": "🔮 For all your Nvidia needs",
  "main": "src/index.ts",
  "scripts": {
    "all": "npm run build && npm run lint",
    "build": "tsc",
    "lint": "xo",
    "lint:fix": "xo --fix",
    "start": "npm run build && node build/index.js",
    "start:dev": "nodemon --config nodemon.json",
    "test:notification": "npm run build && node build/__test__/notification-test.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jef/nvidia-snatcher.git"
  },
  "keywords": [],
  "author": "jef",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jef/nvidia-snatcher/issues"
```

**Comment by ViperRegained** [comment] 2020-11-02 19:44
I have this issue too, im not sure how to fix it.

**Comment by jef** [comment] 2020-11-02 20:07
use `npm i && npm run start`

**Comment by ViperRegained** [comment] 2020-11-02 20:09
The same issue still persists for me. Not sure about the other guy though.

**Comment by jef** [comment] 2020-11-02 20:09
@ViperRegained, can you give me the output?

**Comment by ViperRegained** [comment] 2020-11-02 20:10
"ERR: missing script: start" 
A complete log of this run can be found in:

**Comment by ViperRegained** [comment] 2020-11-02 20:12
When i type npm i it says "up to date in 406ms"

**Comment by jef** [comment] 2020-11-02 20:13
> When i type npm i it says "up to date in 406ms"

`npm` should give something like this:

```
❯ npm        

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview
```

I would make sure that your installation was correct. And perhaps a restart if you're on Windows.

**Comment by jef** [comment] 2020-11-02 20:14
Going to close this issue as it's not a bug in the program, but rather user error (not intended to be harsh).

**Comment by ViperRegained** [comment] 2020-11-02 20:15
Ok, thank you for your help!

**Comment by jef** [comment] 2020-11-02 20:39
You're welcome, did you get it working on your end?

**Comment by ViperRegained** [comment] 2020-11-02 20:40
No sadly, im not sure whats causing it. I just didnt want to bother you.

**Comment by jef** [comment] 2020-11-02 20:41
It's okay. Continue to ask. I get to these questions as best I can, but it also allows others to help! I'm actually going to open back up for visibility so others can comment.

**Comment by ViperRegained** [comment] 2020-11-02 20:43
Oh ok. Thank you! Im just trying to think of whats causing the issue. Ill try to re install everything again from scratch.

**Comment by jef** [comment] 2020-11-02 20:44
Sounds good! Unfortunately I'm not well versed in Windows side of things, only use it to play games mostly. Let me know if it ends up working. Otherwise, we could try to figure out what's going on.

**Comment by ViperRegained** [comment] 2020-11-02 20:48
Yeah still the same issue, even after installing it freshly. I followed the instructions on the page. Do I have to make some sort of bat file that will load something up?

**Comment by ViperRegained** [comment] 2020-11-02 20:53
[2020-11-03T04_47_31_374Z-debug.log](https://github.com/jef/nvidia-snatcher/files/5477949/2020-11-03T04_47_31_374Z-debug.log)

**Comment by jef** [comment] 2020-11-02 21:03
> cwd C:\Users\Administrator

Looks like you're not in the right folder. Make sure you run the `npm i` and `npm run start` inside the `nvidia-snatcher` folder.

**Comment by ViperRegained** [comment] 2020-11-02 21:06
Thank you! I think that might be the issue. Sorry to be a pest but how do i do it inside the folder? Thanks!

**Comment by jef** [comment] 2020-11-02 22:35
No worries!

What you wanna do is `CD` into it.

Some basic instructions are found here: https://github.com/jef/nvidia-snatcher/wiki/Installation:-Windows

**Comment by ViperRegained** [comment] 2020-11-03 19:52
Thank you! Its working now. Only one question. I have it started and its only searching the nvidia store. I renamed the .env-example file and re named to to config.env and I have listed the stores like this: STORES="amazon,asus,bandh,bestbuy,evga,microcenter,newegg,nvidia,officedepot,zotac"

Have I done something wrong? Thank you!

**Comment by jef** [comment] 2020-11-03 22:23
Make sure the `.env` file is file type ENV vs TXT.

**Comment by ViperRegained** [comment] 2020-11-03 22:26
It says its an env file, ill send a picture. 
![image](https://user-images.githubusercontent.com/73852457/98047282-48c31380-1df1-11eb-8d66-9f6cb5f07d35.png)

**Comment by ViperRegained** [comment] 2020-11-03 22:27
Thank you so much for your help by the way, I know im being a pest.

**Comment by jef** [comment] 2020-11-03 22:28
No problem! Really. This is be good to pin after we're done solving.

Can you post your whole `.env`? Redacted any personal information.

**Comment by ViperRegained** [comment] 2020-11-03 22:31
# ** All configuration variables are optional **
# Read https://github.com/jef/nvidia-snatcher#customization for help on customizing this file
#############################################################################################

COUNTRY="usa"
DESKTOP_NOTIFICATIONS=false
DISCORD_NOTIFY_GROUP=@stock
DISCORD_WEB_HOOK=************
EMAIL_PASSWORD=************
EMAIL_TO=*********
EMAIL_USERNAME=*******
IN_STOCK_WAIT_TIME=20
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=900
MICROCENTER_LOCATION=houston
PHONE_CARRIER=att,att
PHONE_NUMBER=******************
PLAY_SOUND=
STORES="amazon,asus,bandh,bestbuy,evga,microcenter,newegg,nvidia,officedepot,zotac"
USER_AGENT=

**Comment by ViperRegained** [comment] 2020-11-03 22:31
I deleted  the other things that I wasnt using. That didnt seem to be the issue before though.

**Comment by jef** [comment] 2020-11-03 22:38
Overall, it looks pretty good. One thing I would suggest is getting the `id` for the `DISCORD_NOTIFY_GROUP`, but that's outside of your problem.

Oh thing I would do is [get your user agent](https://www.google.com/search?q=what+is+my+user+agent).

Next thing I would do is copy this `.env`, back it up on your desktop or something, then use something like this:


```
STORES=amazon,bestbuy,zotac
USER_AGENT=your results from above
```

and see if you get more than nvidia.

**Comment by ViperRegained** [comment] 2020-11-03 22:44
Thank you! I think I figured out what happened, For people in the future what happened was that my brain was turned off and I was saving the .env file in the wrong place. I had to go to the nvidia-snatcher file inside of the current nvidia snatcher file I was already in. Here is a picture so you can see what file to get to: 
![image](https://user-images.githubusercontent.com/73852457/98048689-d869c180-1df3-11eb-8a83-e0300600e3d9.png)

**Comment by jef** [comment] 2020-11-03 22:47
Could be relevant to https://github.com/jef/nvidia-snatcher/issues/658

**Comment by jef** [comment] 2020-11-03 22:48
Glad to hear it's finally working.

**Closed** 2020-11-03 22:47 UTC
Labels: status: help wanted, status: needs discussion, type: question, type: tooling
