### ISSUE TITLE
Customize which browser to open

### ISSUE THREAD

**Issue by gerardmassey** [jef/nvidia-snatcher#221] opened 2020-09-22 23:52 UTC
### Description

Set something in `.env` to open a specific browser. For example, I use Safari primarily but I've had better quick-purchase success with Chrome. In an older iteration of this code, I was able to customize `opn` to launch Firefox.

### Possible solution

Add browser options in `.env`.

**Comment by jef** [comment] 2020-09-24 21:45
Dupe of https://github.com/jef/nvidia-snatcher/issues/282

**Closed** 2020-10-03 17:53 UTC
